services:
  db:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - .env
    networks:
      - app-network

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/src/mev_commit_db
    networks:
      - app-network
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh", "pipeline"]

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: uvicorn api/main.py:app --host 0.0.0.0 --port 8000
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   working_dir: /app/src/mev_commit_db
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network
  #   entrypoint: ["/app/entrypoint.sh", "api"]

networks:
  app-network:
    driver: bridge

volumes:
  clickhouse_data:
    driver: local
